### ISSUE TITLE
Any update plan about the Dataloaders and VRAM usage

### ISSUE THREAD

**Issue by TimandXiyu** [kaixin96/PANet#19]
Hi, it has been very helpful to my on going project.
However, is there any on-going plan that the dataloader could be simplified? Transfering the model to other dataset is really inconvenient.
Another problem: increasing the batchsize dramatically increases the VRAM usage. Not sure whether this is normal or not. And if it is normal, is there anyway to do some optimization?

**Comment by kaixin96** [comment]
@TimandXiyu Sorry for the late reply. I have a plan to reimplement the dataloader part using torchmeta but I am afraid I cannot give you a timeline. Torchmeta has a nice and cleaner interface for general few shot learning problems so reimplementing should not be difficult. You can try coding it yourself.

For the second question, I have not paid much attention to the VRAM usage before. I guess it is due to frequent IO calls. Maybe transferring to torchmeta can help.

**Comment by kaixin96** [comment]
I’m closing this issue because it has been inactive for a while. Feel free to reopen if you have questions. Thank you.
