### ISSUE TITLE
The performence is bad in small target

### ISSUE THREAD

**Issue by gaowq2017** [kaixin96/PANet#20]
Hi@kaixin,
     Thank you for sharing the code and it is helpful for me, but the performence is bad in my datasets that have small target as follow:
![裂纹](https://user-images.githubusercontent.com/29697367/84101590-e2ec7e80-aa40-11ea-8295-26c75ad4c19f.PNG)
There is a crack defect in this picture, the result of miou only is about 0.1 and the visualization is very bad. Do you any suggestions obout this? Thank you very much!
BTW: The size of image is 1488*1488 and the format is .bmp.

**Comment by kaixin96** [comment]
Hi @gaowq2017 , thanks for your feedback. It is not surprising because handling small objects and large input images are still hard problems for segmentation. In my knowledge, using pyramid structure can help improve the performance on small objects. I am not very familiar with handling large input sizes, maybe you can look at some works on Cityscapes dataset. As for your specific task (detecting cracks), I think some methods in edge detection may perform better than segmentation methods.

Thank you.

**Comment by kaixin96** [comment]
I’m closing this issue because it has been inactive for a while. Feel free to reopen if you have questions. Thank you.
